from app.models import db, environment, SCHEMA, Product, User
from sqlalchemy.sql import text


# Adds a product, you can add other products here if you want
def seed_products(users):
    products = [
        {
            # "id": 1,
            "item_name": "Minh's Gundam Mech PC",
            "price": 59999.99,
            "category": "Computer",
            "description": "This is a super PC",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61NlvtrzMVL._AC_SX679_.jpg",
            "sellerId": 5,
        },
        {
            # "id": 2,
            "item_name": "Jenny's Magical Mac",
            "price": 0.99,
            "category": "Computer",
            "description": "This is powered by a potato, but supercharged if Jenny uses it to DJ",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/81yOTN1RvhL._AC_SX679_.jpg",
            "sellerId": 6,
        },
        {
            # "id": 3,
            "item_name": "Chris' One Piece Sound Package",
            "price": 299.99,
            "category": "Computer",
            "description": "This is a one of a life time deal",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/71mj5kFT5IL._AC_SX679_.jpg",
            "sellerId": 4,
        },
        {
            # "id": 4,
            "item_name": "Thandi's Dragon Ball Rage",
            "price": 4.99,
            "category": "Computer",
            "description": "This is a super PC keyboard",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51qHaEKTgxL._AC_SX679_.jpg",
            "sellerId": 7,
        },
        {
            # "id": 5,
            "item_name": "Luffy's Straw Hat Laptop",
            "price": 32.03,
            "category": "Computer",
            "description": "High-performance laptop with advanced features",
            "quantity": 10,
            "preview_imageURL": "https://m.media-amazon.com/images/I/611J00Y94JL._AC_SX679_.jpg",
            "sellerId": 1,
        },
        {
            # "id": 6,
            "item_name": "Luffy's Pirate Jacket",
            "price": 482.40,
            "category": "Clothing",
            "description": "Warm and stylish jacket for winter",
            "quantity": 20,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51jR3ysBmfL._AC_UX679_.jpg",
            "sellerId": 1,
        },
        {
            # "id": 7,
            "item_name": "Sailor Moon Hat",
            "price": 53.23,
            "category": "Clothing",
            "description": "Fashionable hat for all seasons",
            "quantity": 30,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61WGYMalsqL._AC_UX679_.jpg",
            "sellerId": 1,
        },
        {
            # "id": 8,
            "item_name": "Naruto's Hokage Sweater",
            "price": 38.47,
            "category": "Clothing",
            "description": "Cozy sweater for chilly days",
            "quantity": 25,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61lDNn8cZiL._AC_UX679_.jpg",
            "sellerId": 1,
        },
        {
            # "id": 9,
            "item_name": "My Hero Academia Socks",
            "price": 22.29,
            "category": "Clothing",
            "description": "Comfortable socks for everyday wear",
            "quantity": 50,
            "preview_imageURL": "https://m.media-amazon.com/images/I/81tHWmiJ11L._AC_UX679_.jpg",
            "sellerId": 1,
        },
        {
            # "id": 10,
            "item_name": "Dragon Ball Z Shirt",
            "price": 103.54,
            "category": "Clothing",
            "description": "Versatile shirt for any occasion",
            "quantity": 35,
            "preview_imageURL": "https://m.media-amazon.com/images/I/71rE-2t6+YL._AC_UX679_.jpg",
            "sellerId": 1,
        },
        {
            # "id": 11,
            "item_name": "Studio Ghibli Wall Art",
            "price": 234.32,
            "category": "Home Decor",
            "description": "Beautiful wall art inspired by Studio Ghibli films",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/81K61qIYsAL._AC_SX679_.jpg",
            "sellerId": 5,
        },
        {
            # "id": 12,
            "item_name": "Sailor Moon Cushion",
            "price": 938.23,
            "category": "Home Decor",
            "description": "Elegant cushion featuring Sailor Moon design",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61EQfEsXmSL._AC_SX679_.jpg",
            "sellerId": 5,
        },
        {
            # "id": 13,
            "item_name": "Naruto LED Lamp",
            "price": 112.39,
            "category": "Home Decor",
            "description": "Illuminate your room with a Naruto-inspired LED lamp",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51Qyj4sd12S._AC_.jpg",
            "sellerId": 5,
        },
        {
            # "id": 14,
            "item_name": "Dragon Ball Z Coasters",
            "price": 523.93,
            "category": "Home Decor",
            "description": "Protect your furniture with Dragon Ball Z-themed coasters",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/611HU0kfxqL._AC_SX679_.jpg",
            "sellerId": 5,
        },
        {
            # "id": 15,
            "item_name": "My Hero Academia Clock",
            "price": 102.49,
            "category": "Home Decor",
            "description": "Stay punctual with a My Hero Academia-themed clock",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/81NlyjjMRLL._AC_SX679_.jpg",
            "sellerId": 5,
        },
        {
            # "id": 16,
            "item_name": "Sword Art Online Necklace",
            "price": 934.54,
            "category": "Accessories",
            "description": "Elegant necklace inspired by Sword Art Online",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/41nb4H0A7fL._AC_UX679_.jpg",
            "sellerId": 6,
        },
        {
            # "id": 17,
            "item_name": "Attack on Titan Keychain",
            "price": 235.38,
            "category": "Accessories",
            "description": "Carry your keys with an Attack on Titan-themed keychain",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51ZJ4+NwIGL._AC_UX679_.jpg",
            "sellerId": 6,
        },
        {
            # "id": 18,
            "item_name": "Tokyo Ghoul Ring",
            "price": 293.45,
            "category": "Accessories",
            "description": "Unique ring inspired by Tokyo Ghoul",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51eCWGqpQYL._AC_UX679_.jpg",
            "sellerId": 6,
        },
        {
            # "id": 19,
            "item_name": "One Piece Bracelet",
            "price": 309.48,
            "category": "Accessories",
            "description": "Stylish bracelet inspired by One Piece",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61MN4iEseqL._AC_UY695_.jpg",
            "sellerId": 6,
        },
        {
            # "id": 20,
            "item_name": "Naruto Headband",
            "price": 382.93,
            "category": "Accessories",
            "description": "Wear a Naruto headband and embrace the shinobi spirit",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61R3oVrvrcS._AC_UX679_.jpg",
            "sellerId": 6,
        },
        {
            # "id": 21,
            "item_name": "Chopper Chopper Waifu Body Pillow",
            "price": 381.84,
            "category": "Waifu Body Pillows",
            "description": "chopper I need healing!",
            "quantity": 1,
            "preview_imageURL": "https://ae01.alicdn.com/kf/S893cbd93657145f1b7983ff2fee8af357/Hot-35-70cm-Anime-One-Piece-Tony-Tony-Chopper-Stuffed-Plush-Doll-Toy-Bedroom-Decoration-Sleeping.jpg_220x220xz.jpg_.webp",
            "sellerId": 5,
        },
        {
            # "id": 22,
            "item_name": "long duck Waifu Body Pillow",
            "price": 65.37,
            "category": "Waifu Body Pillows",
            "description": "Embrace the beauty of Duck with this body pillow",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61-WOSMiQEL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
            "sellerId": 5,
        },
        {
            # "id": 23,
            "item_name": "Jones Bones Waifu Body Pillow",
            "price": 12.90,
            "category": "Waifu Body Pillows",
            "description": "Hug your bony friend to sleep",
            "quantity": 1,
            "preview_imageURL": "https://rlv.zcache.com/skeleton_body_pillow-rb4d1184959c247cd88f7ad03b704d8d8_z6i08_492.jpg?rlvnet=1",
            "sellerId": 5,
        },
        {
            # "id": 24,
            "item_name": "Chopper ' Waifu ' Body Pillow",
            "price": 744.32,
            "category": "Waifu Body Pillows",
            "description": "",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51YnVfChFpL._AC_UL320_.jpg",
            "sellerId": 5,
        },
        {
            # "id": 25,
            "item_name": "Mikasa Waifu Body Pillow",
            "price": 28.40,
            "category": "Waifu Body Pillows",
            "description": "Feel protected with Mikasa from Attack on Titan on this body pillow",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61cvMMHYBCS._AC_SL1500_.jpg",
            "sellerId": 5,
        },
        {
            # "id": 26,
            "item_name": "Naruto Manga Volume 1",
            "price": 123.94,
            "category": "Books",
            "description": "The first volume of the legendary Naruto manga series",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51VfPmZt5yL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg",
            "sellerId": 1,
        },
        {
            # "id": 27,
            "item_name": "Attack on Titan Manga Volume 1",
            "price": 887.46,
            "category": "Books",
            "description": "The gripping first volume of Attack on Titan manga",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51QWSFImgvL._SY346_.jpg",
            "sellerId": 1,
        },
        {
            # "id": 28,
            "item_name": "One Piece Manga Volume 1-2-3",
            "price": 24.99,
            "category": "Books",
            "description": "Embark on the adventures with One Piece manga volume 1-2-3",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51xr8s57oVL._SX328_BO1,204,203,200_.jpg",
            "sellerId": 1,
        },
        {
            # "id": 29,
            "item_name": "My Hero Academia Manga Volume 1",
            "price": 19.99,
            "category": "Books",
            "description": "Begin the journey of heroes with My Hero Academia manga volume 1",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51cfpB+DHAL._SY344_BO1,204,203,200_.jpg",
            "sellerId": 1,
        },
        {
            # "id": 30,
            "item_name": "Tokyo Ghoul Manga Volume 1",
            "price": 15.49,
            "category": "Books",
            "description": "Experience the world of ghouls with Tokyo Ghoul manga volume 1",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51uWQfEYayL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg",
            "sellerId": 1,
        },
        {
            # "id": 31,
            "item_name": "Studio Ghibli Soundtrack CD",
            "price": 19.99,
            "category": "Music",
            "description": "Enjoy the melodies of your favorite anime with this soundtrack CD",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51rVr8dkd9L._SX466_.jpg",
            "sellerId": 5,
        },
        {
            # "id": 32,
            "item_name": "Naruto Soundtrack CD",
            "price": 12.49,
            "category": "Music",
            "description": "Get into the groove with this popular Naruto album",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61uHIR22d9L.jpg",
            "sellerId": 5,
        },
        {
            # "id": 33,
            "item_name": "One Piece Single",
            "price": 9.99,
            "category": "Music",
            "description": "Relive the excitement of One Piece opening theme with this single",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61MWPBnC0sL.jpg",
            "sellerId": 5,
        },
        {
            # "id": 34,
            "item_name": "Anime Ending Theme Single",
            "price": 9.99,
            "category": "Music",
            "description": "Experience the emotion of the anime's ending theme with this single",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61GU+U+qtTS._SX522_.jpg",
            "sellerId": 5,
        },
        {
            # "id": 35,
            "item_name": "YuYu Hakusho Song Album",
            "price": 14.99,
            "category": "Music",
            "description": "Listen to the character songs of your beloved anime characters with this album",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61DPw6m+GLL._SX466_.jpg",
            "sellerId": 5,
        },
        {
            # "id": 36,
            "item_name": "Naruto Uzumaki Figurine",
            "price": 34.99,
            "category": "Figurines",
            "description": "Bring the hero of the Hidden Leaf Village to your collection",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61z1RE3Q2OL._AC_SX679_.jpg",
            "sellerId": 6,
        },
        {
            # "id": 37,
            "item_name": "Sailor Moon Figurine",
            "price": 29.99,
            "category": "Figurines",
            "description": "Capture the elegance of Sailor Moon in this exquisite figurine",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61T8YWPpQaL._AC_SX679_.jpg",
            "sellerId": 6,
        },
        {
            # "id": 38,
            "item_name": "Dragon Ball Z Goku Figurine",
            "price": 39.99,
            "category": "Figurines",
            "description": "Power up your collection with the iconic Goku figurine",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/71c-lQzlcDL._AC_SY879_.jpg",
            "sellerId": 6,
        },
        {
            # "id": 39,
            "item_name": "My Hero Academia Deku Figurine",
            "price": 26.99,
            "category": "Figurines",
            "description": "Embrace the spirit of heroism with this Deku figurine",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61C84cRTjTL._AC_SX679_.jpg",
            "sellerId": 6,
        },
        {
            # "id": 40,
            "item_name": "Attack on Titan Levi Figurine",
            "price": 42.99,
            "category": "Figurines",
            "description": "Display the strength and determination of Levi in this figurine",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/6168e+KeTFL._AC_SY879_.jpg",
            "sellerId": 6,
        },
        {
            # "id": 41,
            "item_name": "Cool color changing headsets",
            "price": 19.99,
            "category": "Computer",
            "description": "Gaming Headset for PC with Mic PS4/PS5 Xbox One,ENVEL Over-Ear Headphones with Volume Control RGB LED Light Cool Stereo,Noise Reduction for Laptops,Smartphone,Computer",
            "quantity": 6,
            "preview_imageURL": "https://m.media-amazon.com/images/I/71ca3Dw2YvS.jpg",
            "sellerId": 7,
        },
        {
            # "id": 42,
            "item_name": "Kawaii keyboard",
            "price": 29.99,
            "category": "Computer",
            "description": "SELORSS Kawaii Wireless Bluetooth Cute Cat Keyboard,Mini Portable 84Keys Retro Round Keycaps,Quiet Click for Typewriter,Home and Office,Compatible with PC/Mac/Notebook/Laptop/Ipad Air(Pink Colorful)",
            "quantity": 30,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61E9TUWewfL._AC_UF894,1000_QL80_.jpg",
            "sellerId": 7,
        },
        {
            # "id": 43,
            "item_name": "Gaming mouse",
            "price": 50.99,
            "category": "Computer",
            "description": "Cool 4000 DPI Mice 6 LED Buttons Wired USB Optical Gaming Mouse For Pro Gamer_US",
            "quantity": 5,
            "preview_imageURL": "https://i.ebayimg.com/images/g/NFAAAOSwWSlbyuKE/s-l1600.jpg",
            "sellerId": 3,
        },
        {
            # "id": 44,
            "item_name": "Kawaii Frog Mouse pad",
            "price": 16.08,
            "category": "Computer",
            "description": "Kawaii Frog Mouse pad - Cute Frog Mouse Mat - Cute Frog Illustrated Mousemat - Kawaii Mouse mat - Fall Decor - Office Decor",
            "quantity": 8,
            "preview_imageURL": "https://i.etsystatic.com/11663546/r/il/a16b27/2610455987/il_570xN.2610455987_ldki.jpg",
            "sellerId": 7,
        },
        {
            # "id": 45,
            "item_name": "Cute Zero Two Anime",
            "price": 27.77,
            "category": "Computer",
            "description": "laptop skin",
            "quantity": 22,
            "preview_imageURL": "https://ih1.redbubble.net/image.950233661.7889/pd,x500,macbook_air_13-pad,750x1000,f8f8f8.jpg",
            "sellerId": 1,
        },
        {
            # "id": 46,
            "item_name": "Black Cargo pants",
            "price": 15.99,
            "category": "Clothing",
            "description": "Own your inner darkness in these black baggy pants!",
            # Hot n' loaded with metal hardware, these stylish street goth pants feature silver O-rings, buckles, and zipper details. Complete with removable bondage straps and metal eyelets along the waistline. Adjust the accent straps around your legs for the sinfully perfect fit. Zip up the pant legs for a change in style!
            "quantity": 43,
            "preview_imageURL": "https://i.pinimg.com/564x/1f/2f/17/1f2f173c65c43599390ce5ed5437386c.jpg",
            "sellerId": 6,
        },
        {
            # "id": 47,
            "item_name": "EDGY MULTI POCKETS LOW WAIST GRAY PANTS",
            "price": 52.90,
            "category": "Clothing",
            "description": "Old school is back this season so what was popular during 2000’s makes a comeback to our wardrobes just like these Edgy Multi Pockets Low Waist Gray Pants! Combine them with sneakers and a crop top to be fashionable this fall!",
            "quantity": 20,
            "preview_imageURL": "https://cdn11.bigcommerce.com/s-c7qlm8a06j/images/stencil/1280x1280/products/2537/23832/product-image-1845446700__78603.1644014102.jpg?c=1?imbypass=on",
            "sellerId": 3,
        },
        {
            # "id": 48,
            "item_name": "CHEAP GRUNGE T-SHIRT",
            "price": 6.97,
            "category": "Clothing",
            "description": "Gothic T-Shirt Skeleton Print Grunge Aesthetic Goth T Shirt Dark Edgy Fashion Streetwear Graphic Tee",
            "quantity": 25,
            "preview_imageURL": "https://img.joomcdn.net/358773d6ce397492a16a3d16ef817b780ff4936a_original.jpeg",
            "sellerId": 3,
        },
        {
            # "id": 49,
            "item_name": "Japanese demon art face Skull devil oni harajuku aesthetic T-Shirt",
            "price": 15.95,
            "category": "Clothing",
            "description": "Harajuku lovers Oni what do you mean demon, minimal aesthetic streetwear style ninja, shinobi, ronin, yakuza. Minimalistic Stylish Otaku 80s 90s featuring a devil and evil mask hunter and Nippon style. halloween, thanksgiving, birthday, christmas Minimalist Japanese Kanji graphic tee, steamwave for otaku, anime nerd manga geek fan, japanese art culture weeaboo, vaporwave pastel goth punk, soft grunge, urban streetwear street style, feelings of chaos and conflict",
            "quantity": 30,
            "preview_imageURL": "https://m.media-amazon.com/images/I/A13usaonutL._CLa%7C2140%2C2000%7C81HMythsBbL.png%7C0%2C0%2C2140%2C2000%2B0.0%2C0.0%2C2140.0%2C2000.0_AC_UX679_.png",
            "sellerId": 4,
        },
        {
            # "id": 50,
            "item_name": "Trippy Square Pants Long Sleeve Graphic Sweatshirt | Unisex, Up to 4XL",
            "price": 23.99,
            "category": "Clothing",
            "description": "Printed front and back with a rich vibrant design, this long sleeve sweater features a relaxed fit, straight stitched hems, ribbed crew neck and cuffs.",
            "quantity": 30,
            "preview_imageURL": "https://i5.walmartimages.com/asr/b6c1c2d8-1c3b-43d6-8a09-a91edd89a61c.e744f72f2247a34a96558e2e4282fd6f.jpeg?odnHeight=2000&odnWidth=2000&odnBg=ffffff",
            "sellerId": 5,
        },
        {
            # "id": 51,
            "item_name": "OP Pirate Anime Wanted Posters",
            "price": 10.99,
            "category": "Home Decor",
            "description": "New Edition, 28.5cm×19.5cm, Luffy 1.5 Billion, Pack of 24",
            "quantity": 5,
            "preview_imageURL": "https://m.media-amazon.com/images/I/615ovA8lqCL._AC_UF894,1000_QL80_.jpg",
            "sellerId": 7,
        },
        {
            # "id": 52,
            "item_name": "GAVIA Baby Skull Candle Set",
            "price": 5.99,
            "category": "Home Decor",
            "description": "GAVIA Baby Skull Candle Set - Scented - Gothic Decor - Witchy Room Decor - Goth Bedroom Decor - Skull Decor - Horror Decor - Spooky Home Decor - Gothic Home Decor - Witch Decor - Halloween Home Decor",
            "quantity": 6,
            "preview_imageURL": "https://m.media-amazon.com/images/I/81aj17oH5fL.__AC_SY445_SX342_QL70_FMwebp_.jpg",
            "sellerId": 5,
        },
        {
            # "id": 53,
            "item_name": "Black skull lamp",
            "price": 39.99,
            "category": "Home Decor",
            "description": "This die-cut goth table lamp will enhance your gothic decor for bedroom with its sturdy construction and smooth finishing",
            "quantity": 10,
            "preview_imageURL": "https://m.media-amazon.com/images/I/717IYaih2PL.jpg",
            "sellerId": 1,
        },
        {
            # "id": 54,
            "item_name": "Pink Sakura Plush Pillow",
            "price": 28.99,
            "category": "Home Decor",
            "description": "Welcome to our enchanting 45cm Pink Sakura Plush Pillow! This delightful pillow is adorned with adorable kawaii flowers, bringing a touch of whimsy and charm to any space. Its lifelike softness and plush texture make it a perfect companion for relaxation and comfort.",
            "quantity": 15,
            "preview_imageURL": "https://i.etsystatic.com/43642340/r/il/bedfac/5019666540/il_1588xN.5019666540_9g3o.jpg",
            "sellerId": 2,
        },
        {
            # "id": 55,
            "item_name": "Led Gamer Neon Sign Lights Game Controller Neon Sign for Gamer Room Decor Dimmable Neon Lights Gaming Boy Gifts Room Decor",
            "price": 31.49,
            "category": "Home Decor",
            "description": "Led neon signs are made of high-quality copper wire, which has good electrical conductivity and can be used for a long time. the light is soft and will not hurt your hands when you touch it.",
            "quantity": 24,
            "preview_imageURL": "https://ae01.alicdn.com/kf/Sc1c1de4b33fd44c0826345b981b46524C/Led-Gamer-Neon-Sign-Lights-Game-Controller-Neon-Sign-for-Gamer-Room-Decor-Dimmable-Neon-Lights.jpg",
            "sellerId": 2,
        },
        {
            # "id": 56,
            "item_name": "Faux Leather Spike Rivet Choker Punk Necklace Jewelry",
            "price": 2.48,
            "category": "Accessories",
            "description": "Faux leather choker, spike decor, cool and punk. It is a perfect ornament to give you a special look. Suitable for nightclubs, dance hall, parties, holiday, etc.",
            "quantity": 43,
            "preview_imageURL": "https://m.media-amazon.com/images/I/31gx0vc8CNL._AC_.jpg",
            "sellerId": 6,
        },
        {
            # "id": 57,
            "item_name": "FAOYUDAWEI Skull Ring For Men",
            "price": 5.45,
            "category": "Accessories",
            "description": "Retro punk style, suit for vintage motorcycles biker, hip hop, rock and gothic fans. Unique and good workmanship skull ring design for Rock 'n 'roll fans, meticulously crafted in great detail, as well as good cosplay jewelry for halloween party.",
            "quantity": 33,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61FuwABGQxL._AC_UX679_.jpg",
            "sellerId": 6,
        },
        {
            # "id": 58,
            "item_name": "Egirl Aesthetic Skull Chokers",
            "price": 3.26,
            "category": "Accessories",
            "description": "The skull pendant necklace is made of high-quality alloy material, which is durable and wear-resistant. it can be used for a long time.",
            "quantity": 35,
            "preview_imageURL": "https://ae01.alicdn.com/kf/Sd572d22180334eb9956d00392906cc98q.jpg_640x640Q90.jpg_.webp",
            "sellerId": 7,
        },
        {
            # "id": 59,
            "item_name": "Fairy Grunge Aesthetic Belt",
            "price": 13.99,
            "category": "Accessories",
            "description": "Fairy Grunge Aesthetic Belts for Women Fairy Grunge Accessories Grunge Fairycore Jewelry",
            "quantity": 39,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61UcZLIGnkL._AC_UY1000_.jpg",
            "sellerId": 7,
        },
        {
            # "id": 60,
            "item_name": "Black Skull and Awl Earring 925 Sterling Silver",
            "price": 61.95,
            "category": "Accessories",
            "description": "These pair of earrings is made out of 925 sterling silver with black plated metallic finish. Although an ideal accessory for a Halloween party, these also make a perfect addition to Gothic fashion.",
            "quantity": 45,
            "preview_imageURL": "https://www.gnoce.com/media/catalog/product/cache/a95ad56dd2a79ef00be2f8cdc9ab0431/6/1/6110f6fee2569png.png",
            "sellerId": 7,
        },
        {
            # "id": 61,
            "item_name": "Jones Bones 2 Waifu Body Pillow",
            "price": 40.00,
            "category": "Waifu Body Pillows",
            "description": "shiver me timbers 2: electric boogaloo",
            "quantity": 1,
            "preview_imageURL": "https://rlv.zcache.com/boyfriend_skeleton_body_pillow-r3a5c4548fa2e40dab366ac78a7a34878_z6i08_492.jpg?rlvnet=1",
            "sellerId": 5,
        },
        {
            # "id": 62,
            "item_name": "AHHHHHHHHH SHARK Body Pillow ",
            "price": 48.99,
            "category": "Waifu Body Pillows",
            "description": "sheep body pillow (waifu)",
            "quantity": 8,
            "preview_imageURL": "https://rlv.zcache.com/great_white_shark_attack_funny_fish_novelty_ocean_body_pillow-r521240cdd8a642b2a03892115a197ada_z6ibr_492.jpg?rlvnet=1",
            "sellerId": 5,
        },
        {
            # "id": 63,
            "item_name": "The Quintessential Quintuplets Nakano Nino Body Pillow Cover Zipper Anime Body Pillow Cover",
            "price": 40.00,
            "category": "Waifu Body Pillows",
            "description": "Material Peach Skin. The Fabric has a Unique feeling; and a satin-like luster; High Printing Accuracy, Clear patterns, Good Abrasion Resistance, Easy to Clean and Care;",
            "quantity": 4,
            "preview_imageURL": "https://rlv.zcache.com/happy_gary_%e1%95%95_%e1%90%9b_%e1%95%97_meme_emoticon_emoji_text_body_pillow-rb8353932dbdc41fbb7da40ce6e09eebc_z6ibr_492.jpg?rlvnet=1",
            "sellerId": 5,
        },
        {
            # "id": 64,
            "item_name": "Genshin Impact Anime Dakimakura Hugging Body Pillow Case Beelzebul Keqing 150cm Hentai Dakis",
            "price": 6.63,
            "category": "Waifu Body Pillows",
            "description": "sanji? chopper? hello?",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51jWrUKzoEL._AC_UL320_.jpg",
            "sellerId": 5,
        },
        {
            # "id": 65,
            "item_name": "Bread :D",
            "price": 28.00,
            "category": "Waifu Body Pillows",
            "description": "Bread, do not eat, do not wash 'body pillow-waifu-anime",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/615PTC7K0eL._AC_SX679_.jpg",
            "sellerId": 5,
        },
        {
            # "id": 66,
            "item_name": "Jujutsu Kaisen: Jujutsu Kaisen, Vol. 1",
            "price": 7.94,
            "category": "Books",
            "description": "First published in Japan in 2018 by Shueisha Inc., Tokyo -- Title page verso. To gain the power he needs to save his friend from a cursed spirit, Yuji Itadori swallows a piece of a demon, only to find himself caught in the midst of a horrific war of the supernatural!",
            "quantity": 24,
            "preview_imageURL": "https://i5.walmartimages.com/seo/Jujutsu-Kaisen-Jujutsu-Kaisen-Vol-1-Series-1-Paperback-9781974710027_6bee7e19-3dd4-44d5-bb89-6a6c8b38bf6b.8c40c502af450f9d46bb38f8b65510f5.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF",
            "sellerId": 2,
        },
        {
            # "id": 67,
            "item_name": "Zombie Makeout Club Vol 1: DeathWish",
            "price": 10.99,
            "category": "Books",
            "description": "A rebellious high school student is brought back to life in a strange underground facility after commiting suicide. Now, she must piece together not only how and why she has been resurrected, but also confront the fragmented memories of her past and the horrors of the laboratory that want to send her back to the afterlife. This breakneck story illustrates a violent vision of life after death.",
            "quantity": 24,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51umfKp7ekL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg",
            "sellerId": 2,
        },
        {
            # "id": 68,
            "item_name": "Black Butler, Vol. 1 (Black Butler, 1)",
            "price": 13.00,
            "category": "Books",
            "description": "Just a stone's throw from London lies the manor house of the illustrious Phantomhive earldom and its master, one Ciel Phantomhive. Earl Phantomhive is a giant in the world of commerce, Queen Victoria's faithful servant...and a slip of a twelve-year-old boy. Fortunately, his loyal butler, Sebastian, is ever at his side, ready to carry out the young master's wishes. And whether Sebastian is called to save a dinner party gone awry or probe the dark secrets of London's underbelly, there apparently is nothing Sebastian cannot do. In fact, one might even say Sebastian is too good to be true...or at least, too good to be human...",
            "quantity": 30,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51Wip-j7MlL._SX498_BO1,204,203,200_.jpg",
            "sellerId": 4,
        },
        {
            # "id": 69,
            "item_name": "ETERNAL: ILya Kuvshinov Illustration Works",
            "price": 23.06,
            "category": "Books",
            "description": "After the success of Momentary, Ilya has gained popularity and has had some exhibitions and created commercial works. One of the most prestigious jobs Ilya was offered was as the character and visual designer for the anime The Wonderland, directed by Keiichi Hara; Crayon Shin-chan series and Ghost in the Shell: SAC_2045. This talented illustrator, who was influenced by many Japanese artists, now has 1.y million followers on Instagram, and is established as an influencer of other illustrators around the world.",
            "quantity": 24,
            "preview_imageURL": "https://m.media-amazon.com/images/I/41Rz0ZNjFBL._SX398_BO1,204,203,200_.jpg",
            "sellerId": 2,
        },
        {
            # "id": 70,
            "item_name": "Kaiju Girl Caramelise, Vol. 1 (Kaiju Girl Caramelise, 1)",
            "price": 13.00,
            "category": "Books",
            "description": "Suffering from a rare, incurable illness that causes frightening changes to her body, loner Kuroe Akaishi spends her high school days avoiding all her classmates-especially class idol Arata Minami and his groupies. But when Arata starts making her heart skip a beat with irritating regularity, Kuroe discovers that her illness actually has a big-make that MONSTER-secret: Romance turns her into Love-zilla...literally!",
            "quantity": 29,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51Y4dieYGJL._SX351_BO1,204,203,200_.jpg",
            "sellerId": 7,
        },
        {
            # "id": 71,
            "item_name": "Floodland",
            "price": 19.99,
            "category": "Music",
            "description": "Floodland is the second studio album by English gothic rock band the Sisters of Mercy. It was released on 16 November 1987, through Merciful Release internationally and distributed by WEA, with Elektra Records handling the United States release",
            "quantity": 1,
            "preview_imageURL": "https://upload.wikimedia.org/wikipedia/en/3/31/The_Sisters_of_Mercy_-_Floodland_cover_art.png",
            "sellerId": 6,
        },
        {
            # "id": 72,
            "item_name": "Only Theatre of Pain",
            "price": 29.99,
            "category": "Music",
            "description": "Only Theatre of Pain is the debut studio album by the American rock band Christian Death, released on March 24, 1982, by the Frontier record label. It is considered by most critics to be the harbinger of the deathrock style of music, as well as being highly influential on the American gothic music scene.",
            "quantity": 6,
            "preview_imageURL": "https://upload.wikimedia.org/wikipedia/en/9/94/Christian_Death_-_Only_Theatre_Of_Pain.jpg",
            "sellerId": 3,
        },
        {
            # "id": 73,
            "item_name": "Kessoku Band",
            "price": 22.99,
            "category": "Music",
            "description": "Kessoku Band is the debut studio album by Kessoku Band, a fictional musical group from the anime television series Bocchi the Rock!, released digitally on December 25, 2022, and physically on CD on December 28 by Aniplex.",
            "quantity": 24,
            "preview_imageURL": "https://upload.wikimedia.org/wikipedia/en/thumb/3/3e/Kessoku_Band_album_cover.jpg/220px-Kessoku_Band_album_cover.jpg",
            "sellerId": 3,
        },
        {
            # "id": 74,
            "item_name": "μ's Best Album Best Live! collection II",
            "price": 12.99,
            "category": "Music",
            "description": "μ's Best Album Best Live! Collection II is a continuation from μ's Best Album Best Live! Collection, covering the next portion of μ's discography up till the end of the third sub-unit singles.",
            "quantity": 23,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61HDSN3msfL._UF1000,1000_QL80_.jpg",
            "sellerId": 7,
        },
        {
            # "id": 75,
            "item_name": "TV Anime 'Attack on Titan Season 2' (Original Soundtrack)",
            "price": 13.99,
            "category": "Music",
            "description": "'Attack on Titan Season 2' (Original Soundtrack). 2014. Hiroyuki Sawano - Kill la Kill Original Soundtrack. Hiroyuki Sawano.",
            "quantity": 53,
            "preview_imageURL": "https://static.wikia.nocookie.net/shingekinokyojin/images/2/20/Season_2_Original_Soundtrack_Cover.jpg/revision/latest?cb=20170610005221",
            "sellerId": 3,
        },
        {
            # "id": 76,
            "item_name": "CALEMBOU Anime Figure Yae Miko Figure 1/7 PVC Home Decoration Collectible Figurines for Fans",
            "price": 59.99,
            "category": "Figurines",
            "description": "Good choice for any fans. This is a great birthday or Christmas gift for your friends and family who love the Genshin game.",
            "quantity": 9,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61gaX5cG5aL.jpg",
            "sellerId": 5,
        },
        {
            # "id": 77,
            "item_name": "Honkai Impact 3Rd Series Anime Figure Raiden Mei Herrscher of Thunder 1/8 PVC Models Standard and Extended Versions Periphery Models Xmas Gift 25cm",
            "price": 85.98,
            "category": "Figurines",
            "description": "This item is refined hand-tailored & fully customized. Exquisite face and costume carving, attractive look, lifelike pose inspire your imagination. The props are also highly simulated and vivid. The whole part is further polished including skin texture, clothes drape, color and luster, stable base.",
            "quantity": 7,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51qJh40uGUL.jpg",
            "sellerId": 5,
        },
        {
            # "id": 78,
            "item_name": "25cm Japanese Anime One Piece Anime Figure Action Figure Doll Fight Roronoa Zoro Action Figure model Toy",
            "price": 15.98,
            "category": "Figurines",
            "description": "Action Figure |Material: High Quality PVC, Eco-friendly & Non-toxic BTS related",
            "quantity": 23,
            "preview_imageURL": "https://m.media-amazon.com/images/I/41bRjDAzxtL._AC_UF1000,1000_QL80_.jpg",
            "sellerId": 7,
        },
        {
            # "id": 79,
            "item_name": "TAMASHII NATIONS Son Goku Dragon Ball Z, Bandai Imagination Works , Black",
            "price": 54.98,
            "category": "Figurines",
            "description": "Bringing two dimensional characters into vivid three dimension life, using the large format 1/9 scale to achieve rich, fine detail and faithfully detailed coloring for the ultimate in visual appearance.",
            "quantity": 26,
            "preview_imageURL": "https://m.media-amazon.com/images/I/81Qo1uqByfL.jpg",
            "sellerId": 4,
        },
        {
            # "id": 80,
            "item_name": "Banpresto BLEACH Solid And Souls Ichigo Kurosaki Figure",
            "price": 29.90,
            "category": "Figurines",
            "description": "Ichigo is ready to defend your figure shelves from hollows! Add your favorite Soul Reaper to your BLEACH collection with this figure of Ichigo Kurosaki, who's depicted with a serious expression and ready to fight!",
            "quantity": 26,
            "preview_imageURL": "https://cdn.media.amplience.net/s/hottopic/19311492_hi",
            "sellerId": 4,
        },
        {
            # "id": 81,
            "item_name": "Razer DeathAdder V2 Anime Gaming Mouse",
            "price": 49.99,
            "category": "Computer",
            "description": "Enhance your gaming experience with the Razer DeathAdder V2 Anime Edition gaming mouse featuring a stylish anime-themed design and high precision.",
            "quantity": 50,
            "preview_imageURL": "https://assets2.razerzone.com/images/da10m/carousel/razer-death-adder-gallery-15.png",
            "sellerId": 3,
        },
        {
            # "id": 82,
            "item_name": "Attack on Titan Survey Corps Hoodie",
            "price": 34.95,
            "category": "Clothing",
            "description": "Join the Survey Corps and fight against the Titans with this comfortable and stylish hoodie featuring the iconic Wings of Freedom emblem.",
            "quantity": 30,
            "preview_imageURL": "https://cdn11.bigcommerce.com/s-kjvm95bh8i/images/stencil/1280x1280/products/51969/84436/attack-on-titan-survey-corps-logo-hoodie-4__50119.1512223850.jpg",
            "sellerId": 1,
        },
        {
            # "id": 83,
            "item_name": "Studio Ghibli Spirited Away No-Face Lamp",
            "price": 27.50,
            "category": "Home Decor",
            "description": "Illuminate your room with the mysterious No-Face from Spirited Away with this enchanting lamp that changes colors and adds a magical touch to your space.",
            "quantity": 20,
            "preview_imageURL": "https://japantoday-asset.scdn3.secure.raxcdn.com/img/store/54/84/4d6449fbe205a07343f0d489bdfc6ccd9735/Spirited-Away-No-Fac/_w1700.jpg",
            "sellerId": 6,
        },
        {
            # "id": 84,
            "item_name": "My Hero Academia All Might Keychain",
            "price": 9.99,
            "category": "Accessories",
            "description": "Carry the symbol of peace with you everywhere you go with this All Might keychain from My Hero Academia.",
            "quantity": 80,
            "preview_imageURL": "https://m.media-amazon.com/images/I/513gz1UGA3L._AC_UY1000_.jpg",
            "sellerId": 2,
        },
        {
            # "id": 85,
            "item_name": "Kawaii Owel 'Waifu' Body Pillow",
            "price": 39.95,
            "category": "Waifu Body Pillows",
            "description": "Cuddle up with your favorite kawaii waifu with this soft and huggable body pillow featuring an adorable anime character design.",
            "quantity": 15,
            "preview_imageURL": "https://rlv.zcache.com/unique_owl_in_a_row_of_owls_symbolizing_diversity_body_pillow-rc6364721fb344af2800dda4e1b675f89_z6ibr_492.jpg?rlvnet=1",
            "sellerId": 6,
        },
        {
            # "id": 86,
            "item_name": "One Piece Manga Volume 1",
            "price": 12.99,
            "category": "Books",
            "description": "Embark on an epic journey with Monkey D. Luffy and his crew with the first volume of the thrilling One Piece manga series.",
            "quantity": 60,
            "preview_imageURL": "https://prodimage.images-bn.com/pimages/9781421536255_p0_v2_s1200x630.jpg",
            "sellerId": 4,
        },
        {
            # "id": 87,
            "item_name": "Naruto Shippuden Original Soundtrack",
            "price": 19.95,
            "category": "Music",
            "description": "Relive the adventures of Naruto with the iconic soundtrack that captures the emotions and excitement of the series.",
            "quantity": 40,
            "preview_imageURL": "https://i.ebayimg.com/images/g/5hwAAOSwGK1kc3T-/s-l1200.jpg",
            "sellerId": 5,
        },
        {
            # "id": 88,
            "item_name": "Demon Slayer Tanjiro Kamado Figure",
            "price": 32.50,
            "category": "Figurines",
            "description": "Bring the fierce demon slayer, Tanjiro Kamado, to your collection with this beautifully detailed figure capturing his determination to protect his sister.",
            "quantity": 25,
            "preview_imageURL": "https://www.rightstufanime.com/images/productImages/4573102603463_figure-tanjiro-kamado-demon-slayer-figuarts-zero-figure-alta.jpg",
            "sellerId": 2,
        },
        {
            # "id": 89,
            "item_name": "RGB Anime Gaming Keyboard",
            "price": 69.99,
            "category": "Computer",
            "description": "Upgrade your gaming setup with this anime-themed RGB gaming keyboard that offers customizable lighting and smooth key presses.",
            "quantity": 55,
            "preview_imageURL": "https://goblintechkeys.com/cdn/shop/products/league-of-legends-jinx-keycaps-limited-50-set-only-gaming-anime-keycap-sets-keyboard-983976.jpg",
            "sellerId": 1,
        },
        {
            # "id": 90,
            "item_name": "Sailor Moon Luna Cat Ears Headband",
            "price": 14.95,
            "category": "Clothing",
            "description": "Channel your inner Sailor Guardian with this adorable Luna cat ears headband inspired by Sailor Moon's feline companion.",
            "quantity": 35,
            "preview_imageURL": "https://ae01.alicdn.com/kf/H04ce9fe5544b4436b0a8adc0a4da1ab7g/Sailor-Moon-Luna-Cat-Ears-HairBand-Hair-Accessory-Headband-Anime-Cosplay-Cute-Face-Washing-Makeup-Tool.jpg",
            "sellerId": 3,
        },
        {
            # "id": 91,
            "item_name": "My Neighbor Totoro Plush Cushion",
            "price": 24.99,
            "category": "Home Decor",
            "description": "Add a touch of Ghibli magic to your home with this cozy and cute Totoro plush cushion that's perfect for cuddling.",
            "quantity": 28,
            "preview_imageURL": "https://www.worldofghibli.com/wp-content/uploads/2016/09/MNT-Cushions-1.jpg",
            "sellerId": 7,
        },
        {
            # "id": 92,
            "item_name": "Dragon Ball Z Goku Power Pole Keychain",
            "price": 8.95,
            "category": "Accessories",
            "description": "Keep your keys safe with the legendary power pole of Goku from Dragon Ball Z with this eye-catching keychain.",
            "quantity": 90,
            "preview_imageURL": "https://ae01.alicdn.com/kf/S4be608ba8b7748529ece6386fdab15f5a.jpg_640x640Q90.jpg",
            "sellerId": 6,
        },
        {
            # "id": 93,
            "item_name": "Oink Oink Body Pillow",
            "price": 45.50,
            "category": "Waifu Body Pillows",
            "description": "Embrace the fiery and strong-willed Asuka Langley with this huggable body pillow featuring her in a stunning pose.",
            "quantity": 18,
            "preview_imageURL": "https://rlv.zcache.com/funny_6_cartoon_pig_choose_color_body_pillow-rb61e3a2e44444541b6ecda3fbeec53e8_z6ibr_492.jpg?rlvnet=1",
            "sellerId": 5,
        },
        {
            # "id": 94,
            "item_name": "Attack on Titan Manga Box Set",
            "price": 89.95,
            "category": "Books",
            "description": "Experience the intense world of Attack on Titan with this complete manga box set containing all the thrilling volumes.",
            "quantity": 70,
            "preview_imageURL": "https://m.media-amazon.com/images/I/91dwq4-b3uL._AC_UF1000,1000_QL80_.jpg",
            "sellerId": 4,
        },
        {
            # "id": 95,
            "item_name": "Cowboy Bebop OST Vinyl Collection",
            "price": 56.75,
            "category": "Music",
            "description": "Relive the iconic jazz-infused sound of Cowboy Bebop with this limited edition vinyl collection featuring the best tracks from the series.",
            "quantity": 15,
            "preview_imageURL": "https://milan-records.myshopify.com/cdn/shop/products/CowboyBebop_LP_Packshot_Cover_wVinyl_Wide_1382x.jpg?v=1660683906.jpg",
            "sellerId": 3,
        },
        {
            # "id": 96,
            "item_name": "Naruto Uzumaki Kurama Nine-Tails Chakra Mode Figure",
            "price": 39.99,
            "category": "Figurines",
            "description": "Capture the power of the Nine-Tails Chakra Mode with this epic figure of Naruto Uzumaki from the final battle in Naruto Shippuden.",
            "quantity": 20,
            "preview_imageURL": "https://ae01.alicdn.com/kf/S6ee9a94a3099471481ab269c7534f06dI.jpg_640x640Q90.jpg",
            "sellerId": 4,
        },
        {
            # "id": 97,
            "item_name": "Gundam RX-78-2 Model Kit",
            "price": 32.49,
            "category": "Figurines",
            "description": "Build and display the iconic RX-78-2 Gundam with this high-quality model kit, perfect for Gundam enthusiasts and collectors.",
            "quantity": 35,
            "preview_imageURL": "https://www.hlj.com/productimages/ban/bans58205_0.png",
            "sellerId": 2,
        },
        {
            # "id": 98,
            "item_name": "Sword Art Online Alicization VR Game",
            "price": 69.95,
            "category": "Computer",
            "description": "Immerse yourself in the virtual world of Sword Art Online with the thrilling Alicization VR game that brings Kirito's adventures to life.",
            "quantity": 50,
            "preview_imageURL": "https://c4.wallpaperflare.com/wallpaper/600/417/262/video-game-sword-art-online-alicization-lycoris-alice-zuberg-eugeo-sword-art-online-kazuto-kirigaya-hd-wallpaper-preview.jpg",
            "sellerId": 6,
        },
        {
            # "id": 99,
            "item_name": "Tokyo Ghoul Ken Kaneki Mask",
            "price": 24.50,
            "category": "Clothing",
            "description": "Embrace your inner ghoul with this chilling Ken Kaneki mask from Tokyo Ghoul, perfect for cosplay and Halloween.",
            "quantity": 40,
            "preview_imageURL": "https://m.media-amazon.com/images/I/719UW5is5oL.jpg",
            "sellerId": 1,
        },
        {
            # "id": 100,
            "item_name": "My Neighbor Totoro Ceramic Mug",
            "price": 12.95,
            "category": "Home Decor",
            "description": "Enjoy your favorite beverages in the company of Totoro with this adorable ceramic mug featuring the lovable forest spirit.",
            "quantity": 30,
            "preview_imageURL": "https://i.ebayimg.com/images/g/ih8AAOSwyuFecyZ~/s-l1200.jpg",
            "sellerId": 7,
        },
        {
            # "id": 101,
            "item_name": "Neon Genesis Evangelion Rei Ayanami Keychain",
            "price": 9.95,
            "category": "Accessories",
            "description": "Carry the enigmatic Rei Ayanami with you wherever you go with this beautifully crafted keychain from Neon Genesis Evangelion.",
            "quantity": 80,
            "preview_imageURL": "https://i.ebayimg.com/images/g/iqoAAOSw2~ZhJ6W9/s-l1200.jpg",
            "sellerId": 5,
        },
        {
            # "id": 102,
            "item_name": "K-On! Azusa Nakano Figurine",
            "price": 28.99,
            "category": "Figurines",
            "description": "Celebrate the music and friendship of K-On! with this delightful figure of the talented guitarist, Azusa Nakano.",
            "quantity": 25,
            "preview_imageURL": "https://m.media-amazon.com/images/I/71IhNlD8+BL.jpg",
            "sellerId": 3,
        },
        {
            # "id": 103,
            "item_name": "Fullmetal Alchemist Pocket Watch",
            "price": 19.99,
            "category": "Accessories",
            "description": "Transmute your style with this exquisite pocket watch inspired by Fullmetal Alchemist, perfect for any alchemist at heart.",
            "quantity": 60,
            "preview_imageURL": "https://static.wikia.nocookie.net/fma/images/c/c6/Ep._17.jpg",
            "sellerId": 4,
        },
        {
            # "id": 104,
            "item_name": "Sailor Moon Crystal Art Book",
            "price": 32.95,
            "category": "Books",
            "description": "Dive into the enchanting world of Sailor Moon Crystal with this beautiful art book featuring stunning illustrations and character designs.",
            "quantity": 50,
            "preview_imageURL": "https://i.ebayimg.com/images/g/ZmsAAOSwAFlkSBAv/s-l1600.jpg",
            "sellerId": 6,
        },
        {
            # "id": 105,
            "item_name": "Demon Slayer Zenitsu Agatsuma Keychain",
            "price": 8.95,
            "category": "Accessories",
            "description": "Carry the thunderous Zenitsu Agatsuma with you everywhere you go with this charming keychain from Demon Slayer.",
            "quantity": 80,
            "preview_imageURL": "https://bbts1.azureedge.net/images/p/full/2023/01/7998f331-f72e-4608-8840-b172870ff7e5.jpg",
            "sellerId": 7,
        },
        {
            # "id": 106,
            "item_name": "Re:Zero Rem and Ram Wall Scroll",
            "price": 22.99,
            "category": "Home Decor",
            "description": "Adorn your walls with the adorable twin maids, Rem and Ram, from Re:Zero with this elegant wall scroll.",
            "quantity": 25,
            "preview_imageURL": "https://resize.cdn.otakumode.com/ex/500.500/shop/product/f8ad41919a99494e80ecce51a34d4b2a.jpg",
            "sellerId": 1,
        },
        {
            # "id": 107,
            "item_name": "Haikyuu!! Karasuno Volleyball Jersey",
            "price": 34.95,
            "category": "Clothing",
            "description": "Show your support for the Karasuno High volleyball team with this sporty and comfortable jersey from Haikyuu!!.",
            "quantity": 35,
            "preview_imageURL": "https://i.ebayimg.com/images/g/LWIAAOSwDk5T0gp3/s-l1200.jpg",
            "sellerId": 3,
        },
        {
            # "id": 108,
            "item_name": "My Hero Academia Deku Nendoroid",
            "price": 44.99,
            "category": "Figurines",
            "description": "Bring the aspiring hero, Deku, to your collection with this adorable Nendoroid figure featuring various interchangeable expressions.",
            "quantity": 25,
            "preview_imageURL": "https://images.goodsmile.info/cgm/images/product/20161004/5994/41801/large/b6ebd041fc2031586d5402970e8246aa.jpg",
            "sellerId": 1,
        },
        {
            # "id": 109,
            "item_name": "Spirited Away Chihiro Music Box",
            "price": 28.50,
            "category": "Home Decor",
            "description": "Relive the heartwarming moments of Spirited Away with this enchanting music box featuring Chihiro and Haku.",
            "quantity": 20,
            "preview_imageURL": "https://i.etsystatic.com/26788635/r/il/642269/2871580230/il_fullxfull.2871580230_eoto.jpg",
            "sellerId": 3,
        },
        {
            # "id": 110,
            "item_name": "Tokyo Ghoul Kaneki Ken Action Figure",
            "price": 34.95,
            "category": "Figurines",
            "description": "Unleash the power of Kaneki Ken's ghoul form with this highly detailed action figure from Tokyo Ghoul.",
            "quantity": 22,
            "preview_imageURL": "https://i5.walmartimages.com/asr/f98a1ace-0716-476f-9d50-609c703b40b4.71182c33c3a00ff79da7d671c9e74fa6.jpeg",
            "sellerId": 6,
        },
        {
            # "id": 111,
            "item_name": "Naruto Shippuden Rasengan Mousepad",
            "price": 14.95,
            "category": "Computer",
            "description": "Channel the power of Naruto's Rasengan with this stunning mousepad featuring the signature jutsu.",
            "quantity": 50,
            "preview_imageURL": "https://i.etsystatic.com/44456110/r/il/5ae3d7/5038168496/il_fullxfull.5038168496_c4zr.jpg",
            "sellerId": 4,
        },
        {
            # "id": 112,
            "item_name": "One Piece Luffy Straw Hat",
            "price": 18.99,
            "category": "Clothing",
            "description": "Become the future Pirate King with this iconic straw hat worn by Monkey D. Luffy in One Piece.",
            "quantity": 45,
            "preview_imageURL": "https://shutupandtakemyyen.com/wp-content/uploads/2018/12/One-Piece-Luffy-Straw-Hat.jpeg",
            "sellerId": 2,
        },
        {
            # "id": 113,
            "item_name": "Dragon Ball Z Goku Spirit Bomb Lamp",
            "price": 29.50,
            "category": "Home Decor",
            "description": "Light up your room with the power of Goku's Spirit Bomb from Dragon Ball Z with this epic lamp.",
            "quantity": 30,
            "preview_imageURL": "https://i.ebayimg.com/images/g/oE8AAOSwqexhtwao/s-l1200.jpg",
            "sellerId": 5,
        },
        {
            # "id": 114,
            "item_name": "Demon Slayer Water Hashira Giyu Tomioka Statue",
            "price": 39.50,
            "category": "Figurines",
            "description": "Honor the Water Hashira, Giyu Tomioka, with this breathtaking statue capturing his calm and powerful presence from Demon Slayer.",
            "quantity": 18,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51P-WFwzZZL._AC_UF894,1000_QL80_.jpg",
            "sellerId": 2,
        },
        {
            # "id": 115,
            "item_name": "Chopper chopper waifu pillow fluffy",
            "price": 18.75,
            "category": "Waifu Body Pillows",
            "description": "Hug the charming Chopper",
            "quantity": 35,
            "preview_imageURL": "https://ae01.alicdn.com/kf/Hdb594bf3755b4a22a21aff396a6ce565Q/Big-Size-Anime-One-Piece-Chopper-Plush-Stuffed-Doll-Toy-Kawaii-Cute-Lovely-Soft-Plush-Toys.jpg",
            "sellerId": 7,
        },
        {
            # "id": 116,
            "item_name": "Attack on Titan Scout Regiment Backpack",
            "price": 39.95,
            "category": "Clothing",
            "description": "Gear up like a member of the Scout Regiment with this functional and stylish backpack inspired by Attack on Titan.",
            "quantity": 40,
            "preview_imageURL": "https://attackontitanshop.com/wp-content/uploads/2022/01/Anime-Backpack-Attack-on-Titan-Backpack-Cartoon-Canvas-School-Bag-Female-Men-Bagpack-Plecak-Canvas-Travel.jpg",
            "sellerId": 5,
        },
        {
            # "id": 117,
            "item_name": "My Hero Academia Deku Nendoroid",
            "price": 44.99,
            "category": "Figurines",
            "description": "Bring the aspiring hero, Deku, to your collection with this adorable Nendoroid figure featuring various interchangeable expressions.",
            "quantity": 25,
            "preview_imageURL": "https://imgs2.goodsmileus.com/image/cache/data/productimages/Nendoroids/IzukuMidoriya_StealthSuitVer/05-1200x1200.jpg",
            "sellerId": 1,
        },
        {
            # "id": 118,
            "item_name": "Binary? Waifu Pillow",
            "price": 49.95,
            "category": "Waifu Body Pillows",
            "description": "Get cozy with the brooding ghoul, Ken Kaneki, with this high-quality waifu pillow featuring a captivating design.",
            "quantity": 15,
            "preview_imageURL": "https://rlv.zcache.com/arecibo_binary_message_reply_body_pillow-rfcdf5c7a95d44841b4a19fbdc7702c3c_z6i08_492.jpg?rlvnet=1",
            "sellerId": 6,
        },
        {
            # "id": 119,
            "item_name": "Attack on Titan Survey Corps Blanket",
            "price": 29.99,
            "category": "Home Decor",
            "description": "Stay warm and show your allegiance to the Survey Corps with this soft and cozy blanket inspired by Attack on Titan.",
            "quantity": 40,
            "preview_imageURL": "https://i5.walmartimages.com/asr/d40f9bbd-d111-4747-9c29-8b3af99fa374.42fafcb0d692ee075b1366aedd68c629.jpeg",
            "sellerId": 2,
        },
        {
            # "id": 120,
            "item_name": "One Punch Man Saitama Oppai Hoodie",
            "price": 36.95,
            "category": "Clothing",
            "description": "Join the ranks of Saitama's fans with this hilarious Oppai hoodie from One Punch Man, perfect for casual wear or conventions.",
            "quantity": 30,
            "preview_imageURL": "https://i5.walmartimages.com/asr/d7d729fc-aa60-44c7-8cf6-b1faeb302fd6.4abe9b41bf81e67917f0f6236ef0f4ea.jpeg",
            "sellerId": 5,
        },
    ]

    for product in products:
        each_product = Product(**product)
        print(each_product)
        db.session.add(each_product)
        db.session.commit()
    return products


# Uses a raw SQL query to TRUNCATE or DELETE the products table. SQLAlchemy doesn't
# have a built in function to do this. With postgres in production TRUNCATE
# removes all the data from the table, and RESET IDENTITY resets the auto
# incrementing primary key, CASCADE deletes any dependent entities.  With
# sqlite3 in development you need to instead use DELETE to remove all data and
# it will reset the primary keys for you as well.
def undo_products():
    if environment == "production":
        db.session.execute(
            f"TRUNCATE table {SCHEMA}.products RESTART IDENTITY CASCADE;"
        )
    else:
        db.session.execute(text("DELETE FROM products"))

    db.session.commit()
